image: registry.gitlab.com/denrask/opentap-apitest:tap

variables:
  PACKAGE_REPO_URL: "http://packages.opentap.io"
  GIT_DEPTH: ""


stages:
  - build
  - publish


Test:
    stage: build
    tags:
        - gitlab-org
    script:
      - dotnet test WebApiTester.Tests


Build-x64:
  stage: build
  image: mcr.microsoft.com/dotnet/framework/sdk:4.7.2
  tags:
       - windows
  script: 
      - dotnet build WebApiTester -c Release 
      - mv WebApiTester/bin/Release/*.TapPackage .
  artifacts:
      paths:
        - "*.TapPackage"


Build-x86:
  stage: build
  image: mcr.microsoft.com/dotnet/framework/sdk:4.7.2
  tags: [ docker, windows ]
  script: 
      - dotnet build WebApiTester -c Release 
      - mv WebApiTester/bin/Release/*.TapPackage .
  artifacts:
      paths:
        - "*.TapPackage"
