image: registry.gitlab.com/denrask/opentap-apitest:tap

variables:
  PACKAGE_REPO_URL: "http://packages.opentap.io"
  GIT_DEPTH: ""


stages:
  - build
  - publish


Test:
    stage: build
    tags:
        - gitlab-org
    script:
      - dotnet test WebApiTester.Tests

Build:
    stage: build
    tags:
        - gitlab-org
    script:
      - apt-get update
      - apt-get install locales
      - locale-gen en_US.UTF-8
      - dotnet build WebApiTester -c Release 
      - mv WebApiTester/bin/Release/*.TapPackage .
    artifacts:
      paths:
        - "*.TapPackage"


